[project]
name = "rez-bootstrap"
version = "0.0.1"
dependencies = [
    "rez>3",
    "requests",
    "zstandard",
    "rich",
]

[project.scripts]
rez-bootstrap = "rez_bootstrap._cli:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
